apiVersion: v1
kind: Service
metadata:
  name: dummy-microservice-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: dummy-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
